### ISSUE TITLE
Implement "vstack"

### ISSUE THREAD

**Issue by isaacsanders** [elixir-nx/explorer#129]
Right now it doesn't seem there is a way to concatenate DataFrames. There is a function for this: https://docs.rs/polars/0.14.2/polars/frame/struct.DataFrame.html#method.vstack

**Comment by cigrainger** [comment]
We’ve got this one. It’s `Explorer.DataFrame.concat_rows`. https://github.com/elixir-nx/explorer/pull/76

**Comment by isaacsanders** [comment]
I missed that. Are there docs somewhere that make it easier to discover the API? I was using the livebook when I was looking for this.

**Comment by cigrainger** [comment]
Yep! The sidebar has https://elixir-nx.github.io/explorer, which is where our docs are living until a Hex release.

**Comment by isaacsanders** [comment]
@cigrainger Why is the name different than the existing Elixir APIs and the existing Polars APIs? Creating a different name feels like it would require a pretty significant reason.

**Comment by isaacsanders** [comment]
> Yep! The sidebar has https://elixir-nx.github.io/explorer, which is where our docs are living until a Hex release.

This will be super helpful, thanks!

**Comment by cigrainger** [comment]
The name is a combination of pandas' concat and dplyr's bind_rows. It's basically the former but specifying the axis. Re: the latter, bind was chosen because concat was taken.

**Comment by josevalim** [comment]
I think I was the one who mentioned `concat_rows` but if we go with dplyr naming everywhere, then maybe it should be `bind_rows`? Is there any other API where we diverge the naming? :)

**Comment by cigrainger** [comment]
We diverge in a few places. And dplyr had to deal with avoiding naming collisions due to the way R is commonly used. dplyr differs from data.table, which differs from pandas, which differs from polars, which differs from DataFrames.jl. In most cases the APIs have minute differences due to the philosophy behind them or the language used and the naming corresponds to that. I don't think that we're running amiss of anything by trying to choose the best naming for the way our API works (within reason).
