### ISSUE TITLE
Create a shared vocabulary for data conversions

### ISSUE THREAD

**Issue by josevalim** [elixir-nx/explorer#167]
We need to define a vocabulary for converting dataframes in and out of different formats, using different representations. For example, if we take CSV as an example, we may need to:

1. read CSV from file
2. read CSV from a binary (i.e. from memory/buffer)
3. write dataframe as a CSV file
4. convert dataframe to a CSV binary (i.e. to memory/buffer)

We need to provide a similar API for different formats. We already support IPC. And others may come in the future (parquet? json? etc).

For example, one idea is (respective to the above):

1. read_csv
2. parse_csv
3. write_csv
4. to_csv

And them similar for ipc and so on.

**Comment by josevalim** [comment]
We may also need other functionality in the future, such as `to_csv_stream`, which streams the CSV instead of writing a huge blob. Or even have `to_csv_iodata`, in case we don't want to build a large binary upfront.

**Comment by kimjoaoun** [comment]
I confess I'm not comfortable with using just "to_csv" as it might be a source of confusion for people that are used to working with data in another languages. (See [Pandas.DataFrame.to_csv](https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.to_csv.html)).
I think preferable to use something like `deparse_csv` or even that `to_csv_binary` name.

**Comment by cigrainger** [comment]
We actually support Parquet already as well. I'll take a bit of time today to research this. My only real concern is that the use cases for each of the formats may differ considerably. 

For example, delimited files make sense as a binary representation. IPC has baggage to consider on that front ([in memory it should be a streaming file format](https://arrow.apache.org/docs/format/Columnar.html#ipc-streaming-format), and I think it would be confusing to basically just read the file as an opaque binary). Parquet and IPC are often used for OLAP purposes and IPC in particular is meant to be memory mapped for random access (see [Wes McKinney's](https://stackoverflow.com/a/56481636) explanation). So for example would `to_ipc` give you a record batch format? (I think it may be clearer to refer to it as `arrow` instead of `ipc`). 

None of this really detracts from the point that it makes sense to have read/write to/from disk/memory as a basic set of verbs. Just noting that Parquet and IPC/Arrow aren't direct cognates to delimited files and so the naming should consider that.

By the by @kimjoaoun I agree on the possible source of confusion. I note that [`to_csv`](https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.to_csv.html#pandas-dataframe-to-csv) is used for _both_ memory and file and honestly that may be the best approach? [`from_csv`](https://pandas.pydata.org/docs/reference/api/pandas.read_csv.html) is the same. That's basically what [`readr`](https://readr.tidyverse.org/reference/read_delim.html) does as well.

**Comment by cigrainger** [comment]
Sorry didn't mean to close -- fat fingers. :)

**Comment by josevalim** [comment]
> For example, delimited files make sense as a binary representation. IPC has baggage to consider on that front ([in memory it should be a streaming file format](https://arrow.apache.org/docs/format/Columnar.html#ipc-streaming-format), and I think it would be confusing to basically just read the file as an opaque binary).

The issue is that we may want to read an IPC file from S3 or URL. In this case, our only option is to either read into memory and then pass to Explorer. Otherwise we would need to add all of this functionality directly to explorer.

At the same time, we most likely want to avoid reading the whole binary into memory first? I don't know... maybe it depends on the format. Some of the IPC examples I saw about reading from S3, they all read the dataset into memory first. Alternatively we could try to come up with a reader API, if it makes sense. Something like this:

    stream_ipc() :: handle()
    stream_ipc(handle(), binary | :eof) :: {:more, ..., handle} | {:done, ...}

> I note that [to_csv](https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.to_csv.html#pandas-dataframe-to-csv) is used for both memory and file and honestly that may be the best approach? [from_csv](https://pandas.pydata.org/docs/reference/api/pandas.read_csv.html) is the same. That's basically what [readr](https://readr.tidyverse.org/reference/read_delim.html) does as well.

It may be possible to implement some sort of streaming `to_csv`, which would allow us to write to memory, disk, etc using the same output. So we could do `to_csv |> File.into(File.stream(...))` to write to file. `to_csv |> Enum.to_list |> IO.iodata_to_binary` to get a binary. But even then, we may want to provide a shortcut for getting the binary itself.

**Comment by cigrainger** [comment]
I'm comfortable with that. I like load/dump personally. I think because postgresql. Also json in python uses that.
