### ISSUE TITLE
Complement `from_rows` and `from_columns` with `to_rows` and `to_columns`

### ISSUE THREAD

**Issue by cigrainger** [elixir-nx/explorer#169]
I think instead of `to_map` we should have `to_rows` (which would yield a list of maps) and `to_columns` which would yield a map of lists. That way the functions have symmetry.

**Comment by josevalim** [comment]
With `table`, I actually want to get rid of `from_rows` and `from_columns` because we want to allow any data to be passed in and we will convert it on the best way possible. In this sense, should we keep it as `to_map` and `to_list` or would you still rename it to `to_rows` and `to_columns`? FWIW, `Table.to_rows` and `Table.to_columns` is also the nomenclature that we use, so we would be consistent.

**Comment by jonatanklosko** [comment]
@josevalim ah, so we still want to mirror both functions under `Explorer.Dataframe`?

**Comment by cigrainger** [comment]
I'm not sure #178 closes this. I think mirroring makes sense to me.

**Comment by jonatanklosko** [comment]
Makes sense! It actually has different semantics because `to_columns`/`to_map` returns series, please reopen :D
