### ISSUE TITLE
Blob column type

### ISSUE THREAD

**Issue by LostKobrakai** [elixir-nx/explorer#182]
I've been investigating parquet and explorer in the last few days for a set of data, which includes raw binaries. I can base 64 encode them, but I'd expect that to introduces a bunch of overhead in size. Would it be possible to have a raw binary column type?

**Comment by cigrainger** [comment]
Now that Explorer is off the ground a bit I'd generally like to add more column types. In theory `polars` supports [opaque binaries](https://docs.rs/polars/latest/polars/datatypes/enum.ArrowDataType.html#variant.Binary) because `arrow` does. I'm not sure what the equivalent `polars` type is. I think [Object](https://docs.rs/polars/latest/polars/datatypes/struct.ObjectType.html). @ritchie46 is that the right way to go?
