### ISSUE TITLE
Across APIs

### ISSUE THREAD

**Issue by josevalim** [elixir-nx/explorer#223]
@cigrainger and I were discussing ideas to improve the dataframe API. One of the ideas is to bring dplyr's [recent `across`  functionality](https://gist.github.com/josevalim/342728a5b2434569704fe129ff84d228), so we can do:

    |> DF.filter(across(sepal_width < 10))

Or even to filter across multiple columns:

    |> DF.filter(across(col <- [sepal_width, petal_width], col < 10))

However, @cigrainger mentioned that we may want to just make `DF.filter/2` a macro, so we can write this:

    |> DF.filter(col <- [sepal_width, petal_width], col < 10)

The following operations need to support `across` (or will need to be macros): arrange, filter, summarize, and mutate. The goal is to discuss if we should go with explicit `across` OR use macros.

## `across` or macros

The benefit of `across` is Explorer will have a single macro, `across`, which we will get from `import Explorer`. However, we will need to type `across` almost every time we use one of the operations above, which would make them more verbose.

Macros solve the verbosity problem, at the cost of adding more magic. Also, for every macro API, we should have a non-macro version. However, I think we can easily tackle this by having a `_with` suffix convention. `filter/2` is a macro, that supports the across functionality. `filter_with/2` is the version that supports anonymous functions. Then we can have similar with `mutate` and `mutate_with` and so on.

@cigrainger, do you have any further thoughts on the preferred approach?

**Comment by cigrainger** [comment]
Oh I really like the `_with` suffix idea! I think having the macro version of filter/mutate/summarise means that _eager_ polars can use the lazy API behind the scenes to permit a more flexible API. This is particularly important for summarise, which right now is really polars-specific and lacking functionality. I also think this will be important for a SQL backend to avoid the need to copy from local to source.

**Comment by josevalim** [comment]
>  but also the ability to always use contextual instructions instead of realising a series immediately.

To clarify, this will always be true for both APIs! We can change `DF.filter(..., fn df -> ... end)` (or `DF.filter_with`) so the dataframe received in the function always yields a "LazySeries". Which is why I think we should split `filter` in two functions (`filter` and `mask` - but you may have better ideas for the second name, see #224).

The same for mutate:

```elixir
DF.summarize(df, fn df -> [width_avg: Series.average(df["width"])] end)
```

`df` will emit lazy series so we can compute all values properly.

So the two approaches discussed here should only be a style-related choice. Although I also like your idea of supporting the macro syntax and using `across` only for when folks want to traverse multiple columns. If we go this route, my only question is where should the `across` macro live.

**Comment by cigrainger** [comment]
I didn't even consider it, but I see your point that we can just convert to lazy before applying the callback on the back end and that will provide lazy series. I also like requiring the second argument as a single callback that returns a keyword list instead of a keyword list of callbacks (or raw values).

The raw value thing is a challenge that you've identified in #224. I think `_with` suffixes make plenty of sense here and can be uniform across the verbs (instead of `mask` or other verb-specific functions). Like `arrange_with`. It makes sense to me that we're doing this verb "with" this realised Series/list.

So what are the other drawbacks of using a macro instead of a callback? On the one hand, I think Elixir syntax is "tidy enough"... on the other, I think vectorised infix operators are more natural as are unwrapped column names. 

Compare:

```elixir
DF.summarize(df, fn df -> [width_avg: Series.average(df["width"])] end)
```

to

```elixir
DF.summarize(df, width_avg: Series.average(width))
```

Honestly, I'm wondering if we need to settle on this right away. I think there would be plenty of immediate benefit in locking down the non-macro API:

1. Replace keyword list of callbacks/values to a single callback returning a keyword list
2. Discourage raw/realised Series/list use in filter, arrange, et al by only taking a callback and providing `filter_with` and `arrange_with` instead (could also be `_by`).
3. Change the backend to use lazy under the hood with the callbacks
4. Change the `group_by`/`summarise` API to more closely resemble `mutate`
5. Assess whether we should use the macro syntax

One thing I'll note is that providing `across` without using the macro syntax elsewhere may be confusing -- folks might think they can use the macro syntax when they can't, and it confuses the point of `across` which is to traverse multiple columns. I think we should basically do both or neither. I lean towards both, but also think it may be a moving target before we do the steps above.

**Comment by josevalim** [comment]
> Honestly, I'm wondering if we need to settle on this right away. I think there would be plenty of immediate benefit in locking down the non-macro API:

I agree we should do this asap because this change is orthogonal to `across`. This discussion is mostly about choosing the API, not the functionality, and I think the functionality could have immediate use!

I also agree with our list steps too. Until we have the macro versions, I think we should only have `filter_with` and `arrange_with`. For functions that receive realized series, maybe they should have a different name, especially because the functions that work with realized series most likely won't work on lazy backends? Are there any other functions you believe we should expose the realized series API besides `filter`? If so, we can continue the discussion in #224.

**Comment by josevalim** [comment]
> I think we should only have filter_with, arrange_with, etc

Actually, keep the existing APIs around, introduce the new ones, and then replace the old ones by macros when ready.

**Comment by josevalim** [comment]
For completeness, the operations that will be affected by this are: mutate, summarize, filter, arrange, distinct.

---

Although `arrange`/`distinct` introduce one particular issue. We have added the `_with` prefix to disambiguate the macro-api from the non-macro API. This was easy because the non-macro API for `mutate`/`summarize`/`filter` are function based. However, `arrange`/`distinct` already have a non-macro API that is not function based, for example:

    arrange(df, desc: "my_field")

But we also want to support this:

    arrange(df, desc: my_field)

We have three choices:

  * Keep `arrange(df, desc: "my_field")` and `arrange(df, desc: my_field)`, under the same function/arity. This may be doable but it may also raise ambiguities. For example, should we allow `arrange(df, desc: my_field, asc: "another-field")`?

  * Move the non-macro API to `arrange_with`, which will support keywords or functions, such as `arrange_with(df, desc: "my_field")`

  * Remove the `arrange(df, desc: "my_field")` version. People can either use `arrange(df, desc: my_field)` or `arrange_with(df, fn df -> [desc: df["my_field"]] end)`
