### ISSUE TITLE
Series.min/1 throws error on integer series

### ISSUE THREAD

**Issue by srowley** [elixir-nx/explorer#287]
Seems similar to #242.

Erlang/OTP 25 [erts-13.0.1] [source] [64-bit] [smp:8:8] [ds:8:8:10] [async-threads:1] [jit:ns]
Elixir 1.13.4 (compiled with Erlang/OTP 25)
Explorer 0.2.0

```
alias Explorer.{Datasets, DataFrame, Series}

Datasets.fossil_fuels()
|> DataFrame.group_by("country")
|> DataFrame.summarise(total: [:count])
|> DataFrame.pull("total_count")
|> Series.min()
```

Expected output: a number

Actual output:
```
** (ErlangError) Erlang error: :nif_panicked
    (explorer 0.2.0) Explorer.PolarsBackend.Native.s_min(shape: (222,)
Series: 'total_count' [u32]
[
	5
        [truncated a long list of 5's and 3's]
        ...
	3
])
    (explorer 0.2.0) lib/explorer/polars_backend/shared.ex:17: Explorer.PolarsBackend.Shared.apply_series/3
```

**Comment by philss** [comment]
The problem is that some operations return `Series` that are from types we don't handle. In this example the series returned by the summarised DF is from the type `UInt32`, but we only handle `Int64` for integers.  See:
https://github.com/elixir-nx/explorer/blob/607e612d449bc9b2f8adfd93ea60027374256dc3/native/explorer/src/series.rs#L480-L487

We need to cast the resultant aggregations or [handle more types](https://docs.rs/polars-core/0.22.7/polars_core/datatypes/enum.DataType.html). I think it's better in terms of performance to handle the additional dtypes. @cigrainger what do you think?

PS: this works:

```elixir
alias Explorer.{Datasets, DataFrame, Series}

s =
  Datasets.fossil_fuels()
  |> DataFrame.group_by("country")
  |> DataFrame.summarise(total: [:count])
  |> DataFrame.pull("total_count")

s |> Series.to_list() |> Series.from_list() |> Series.min()
```

**Comment by josevalim** [comment]
We have two options:

1. Support more types internally.
2. Support more types and also expose them to users. This means our types are `:u8`, `:u16`, `:s64`, `:f32`, `:f64`, and so on.

Which route are we supposed to take?

**Comment by philss** [comment]
I would go first with `1.` and then we decide if we want to expose more types.
