### ISSUE TITLE
Implement not implemented functions for lazy series

### ISSUE THREAD

**Issue by nallwhy** [elixir-nx/explorer#381]
```elixir
# The following functions are not implemented yet and should raise if used.
funs = [
  memtype: 1,
  fetch!: 2,
  mask: 2,
  from_list: 2,
  sample: 4,
  size: 1,
  slice: 2,
  take_every: 2,
  to_enum: 1,
  to_list: 1,
  transform: 2
]
```

### Functions that should be implemented
- [ ] `mask/2`
- [x] `sample/4` - https://github.com/elixir-nx/explorer/pull/385
- [x] `size/1` - https://github.com/elixir-nx/explorer/pull/385
- [ ] `slice/2`
- [ ] `take_every/2`

### Functions that NOT should be implemented

- `memtype/1`
- `fetch!/2`
- `from_list/2`
- `to_enum/1`
- `to_list/1`
- `transform/2`

**Comment by nallwhy** [comment]
@josevalim @philss Please check it's correct

**Comment by josevalim** [comment]
We cannot implement `fetch!` because it requires getting a value from something lazy (which has no value).

We cannot implement `transform` because it requires Elixir functions, and we cannot convert those to backend operations (such as Rust, SQL queries, etc).

You may be able to implement the others... but not guaranteed.

**Comment by nallwhy** [comment]
Thanks!
