### ISSUE TITLE
Applying a function/transform on grouped series

### ISSUE THREAD

**Issue by miXwui** [elixir-nx/explorer#400]
I'm trying to transform data like this:
| a | b |
|---|---|
| 1 | a |
| 1 | b |
| 2 | c |
| 2 | d |

By first grouping by column `a` and then concatenating all values in column `b` within each group.
Result:
| a | b_merged |
|---|---|
| 1 | a, b |
| 2 | c, d |

Code:
```elixir
Explorer.DataFrame.new(a: ["1", "1", "2", "2"], b: ["a", "b", "c", "d"])
|> Explorer.DataFrame.group_by(:a)
|> Explorer.DataFrame.summarise_with(fn df ->
  [
    b_merged: df["b"] |> Explorer.Series.to_list() |> Enum.join(", ")
  ]
end)
```

```text
** (RuntimeError) cannot perform operation on an Explorer.Backend.LazySeries
    (explorer 0.4.0-dev) lib/explorer/backend/lazy_series.ex:486: Explorer.Backend.LazySeries.to_list/
 ```
Possibly related:
https://github.com/elixir-nx/explorer/issues/381

Similarly with dplyr:
https://stackoverflow.com/questions/38514988/concatenate-strings-by-group-with-dplyr

In Polars Python, I do something like this:
```python
import polars as pl

df = pl.DataFrame({"a": ["1", "1", "2", "2"], "b": ["a", "b", "c", "d"]})

df.groupby(["a"]).agg(
  [
    pl.col("b").apply(lambda c: ", ".join(c)),
  ]
)
```

I also tried using `mutate_with` to no avail :(

Thanks in advance!

**Comment by philss** [comment]
This is not possible today. But I think with the addition of the [list dtype](https://github.com/elixir-nx/explorer/issues/296) we could easily do something similar to that.

Unfortunately `Explorer.Series.to_list/1` won't work as expected inside the `summarise_with` or `mutate_with` because there is no way to fetch the data at that point because all data is lazy inside those functions.

I will investigate the surface of the list dtype addition.
Thanks for the report!

**Comment by miXwui** [comment]
Ah, now I understand why. Thanks for the explanation and much appreciated @philss!
