### ISSUE TITLE
`Explorer.DataFrame.new/1` does not support series with binaries

### ISSUE THREAD

**Issue by srowley** [elixir-nx/explorer#458]
I am trying to create a data frame from a list of maps, where one element in the map has binary data. I verified that I can create a series from that element, but `Explorer.DataFrame.new/1` fails when called with the entire dataset.

Example:

```
iex(6)> row
%{
  lower: 17.0,
  middle: 17.5,
  outliers: <<131, 107, 0, 8, 12, 12, 23, 24, 25, 25, 26, 27>>,
  upper: 19.0,
  ymax: 22,
  ymin: 14
}

iex(7)> Explorer.Series.from_list([row.outliers], dtype: :binary)
#Explorer.Series<
  Polars[1]
  binary [<<131, 107, 0, 8, 12, 12, 23, 24, 25, 25, 26, 27>>]
>

iex(8)> Explorer.DataFrame.new([row])                            
** (ArgumentError) cannot create series "outliers": argument error
    (explorer 0.4.0) lib/explorer/polars_backend/data_frame.ex:335: Explorer.PolarsBackend.DataFrame.series_from_list!/2
    (elixir 1.14.2) lib/enum.ex:1658: Enum."-map/2-lists^map/1-0-"/2
    (elixir 1.14.2) lib/enum.ex:1658: Enum."-map/2-lists^map/1-0-"/2
    (explorer 0.4.0) lib/explorer/polars_backend/data_frame.ex:288: Explorer.PolarsBackend.DataFrame.from_tabular/1
    iex:8: (file)
```

**Comment by josevalim** [comment]
Does it work if you pass the dtypes option to new?

**Comment by srowley** [comment]
It works in `Explorer.Series.from_list/1` as shown in the example, but I don't see that option or any other way to specify dtypes in `Explorer.DataFrame.new/1`.

**Comment by Jhonatannunessilva** [comment]
As I understand it, this happens because the function [check_types!/2](https://github.com/elixir-nx/explorer/blob/51dd101cd995863561583982f1c2795cd1f497d6/lib/explorer/shared.ex#L109) is returning ":string" for the type of this series.

Currently, the only way for this function to return ":binary" instead of ":string" is if the variable "preferable_type" equals ":binary" ([type/2](https://github.com/elixir-nx/explorer/blob/51dd101cd995863561583982f1c2795cd1f497d6/lib/explorer/shared.ex#L140)).

Unfortunately at the moment, this variable is never sent when the [DataFrame.new/2](https://github.com/elixir-nx/explorer/blob/c7c01463333bb330a6b57ceb5d2e04a41b631288/lib/explorer/data_frame.ex#L1269) function is called.

Perhaps the "DataFrame.new/2" function could accept the "dtype: :binary" option and pass that value to the "check_types!/2" function. But if that change is made, you probably need to change [this](https://github.com/elixir-nx/explorer/blob/51dd101cd995863561583982f1c2795cd1f497d6/lib/explorer/shared.ex#L120) to:
```elixir
cond do
  new_type == :numeric and type in [:float, :integer] ->
    new_type

  #                                  vvvvvvvvvvvvvvvvv
  new_type != type and type != nil and type != :binary ->
    raise ArgumentError,
    "the value #{inspect(el)} does not match the inferred series dtype #{inspect(type)}"

  true ->
    new_type
end
```

**Comment by philss** [comment]
> Perhaps the "DataFrame.new/2" function could accept the "dtype: :binary" option and pass that value to the "check_types!/2" function.

@Jhonatannunessilva yeah, I think this is the way to go. Thanks!

@josevalim @srowley I'm going to add the `:dtypes` option to `new/2`, since we can't tell if it's a string or regular binary.

**Comment by philss** [comment]
@Jhonatannunessilva actually, do you want to give it a try? I think we need to:
- change the `DataFrame.new/2` to accept the `:dtypes` option (like we have in the `from_csv`);
- change the `DataFrame` backend (`Backend.DataFrame`) callbacks `from_tabular` and `from_series` to accept the dtypes option (maybe accept opts directly);
- and then change the callback implementations for the polars backend.

WDYT?

**Comment by Jhonatannunessilva** [comment]
@philss Yes, I can try!

**Comment by philss** [comment]
@Jhonatannunessilva nice! Let me know if you need some help :)

**Comment by Jhonatannunessilva** [comment]
@philss All tests pass when I run "mix ci", but I have a few questions:

- Why does the `from_series` callback need to receive the `dtypes` option?
  - Since this is a "from series" operation, the sent "series" has already been created with the types correctly, right?
  - For example (the example works without the changes):
```elixir
# If I try to create a "series" with binary content without sending the "dtype" option an error will be returned:
iex> series = Explorer.Series.from_list([<<239, 191, 19>>])
** (ArgumentError) argument error
    (explorer 0.5.0-dev) Explorer.PolarsBackend.Native.s_from_list_str("", [<<239, 191, 19>>])
    (explorer 0.5.0-dev) lib/explorer/polars_backend/series.ex:19: Explorer.PolarsBackend.Series.from_list/2
    (explorer 0.5.0-dev) lib/explorer/series.ex:191: Explorer.Series.from_list/2

# So the only way I can create this "series" is by sending the "dtype" option:
iex> series = Explorer.Series.from_list([<<239, 191, 19>>], dtype: :binary)
#Explorer.Series<
  Polars[1]
  binary [<<239, 191, 19>>]
>

# Then I can try to do the "DataFrame.new/2" (from "series"):
iex> Explorer.DataFrame.new(%{binaries: series})
#Explorer.DataFrame<
  Polars[1 x 1]
  binaries binary [<<239, 191, 19>>]
>
```
- In the [`from_tabular`](https://github.com/elixir-nx/explorer/blob/c7c01463333bb330a6b57ceb5d2e04a41b631288/lib/explorer/backend/data_frame.ex#L123) callback is it better to send `dtypes` or `opts`?
  - In the [`from_csv`](https://github.com/elixir-nx/explorer/blob/c7c01463333bb330a6b57ceb5d2e04a41b631288/lib/explorer/backend/data_frame.ex#L32) and [`load_csv`](https://github.com/elixir-nx/explorer/blob/c7c01463333bb330a6b57ceb5d2e04a41b631288/lib/explorer/backend/data_frame.ex#L49) callbacks the `dtypes` are sent directly.
  - So, I am sending the "dtypes" option directly.
- Where should I write the test that reproduces this bug?
  - At the moment, I put it in the [doctests](https://github.com/elixir-nx/explorer/blob/c7c01463333bb330a6b57ceb5d2e04a41b631288/lib/explorer/data_frame.ex#L1205) of the `DataFrame.new/2` function. (from what I understand, all the tests of this function are there).
  - Test I added:
```elixir
  iex> Explorer.DataFrame.new(%{floats: [1.0, 2.0], ints: [1, nil], binaries: [<<239, 191, 19>>, nil]}, dtypes: [{:binaries, :binary}])
  #Explorer.DataFrame<
    Polars[2 x 3]
    binaries binary [<<239, 191, 19>>, nil]
    floats float [1.0, 2.0]
    ints integer [1, nil]
  >
```

**Comment by josevalim** [comment]
> Why does the from_series callback need to receive the dtypes option? 

If it doesn't need to receive the options, even better.

> In the [from_tabular](https://github.com/elixir-nx/explorer/blob/c7c01463333bb330a6b57ceb5d2e04a41b631288/lib/explorer/backend/data_frame.ex#L123) callback is it better to send dtypes or opts?

dtypes for consistency

> Where should I write the test that reproduces this bug? 

A separate test on data_frame_test.exs would be great :)

**Comment by philss** [comment]
> Why does the `from_series` callback need to receive the dtypes option? 

I think we can ignore `dtypes` for `from_series/1`. My initial thought was to cast if the types differ. But I think we can ignore this for now. We should add a note in the docs about this behaviour. :)
