### ISSUE TITLE
Return {:error, string} instead of {:error, {:polars, string()}}

### ISSUE THREAD

**Issue by josevalim** [elixir-nx/explorer#584]

**Comment by Jhonatannunessilva** [comment]
Can you send an example?

**Comment by philss** [comment]
hey @Jhonatannunessilva :wave: 

The problem appears when we use a function from the `Explorer.PolarsBackend.Native` module and the function returns an error. It is in this tuple format, but we really want just the string.

Here is where it's being encoded: https://github.com/elixir-nx/explorer/blob/441d21909910960d54bfb91479d3774324984c65/native/explorer/src/error.rs#L37-L54

I think we can leverage the power of [`thiserror`](https://github.com/dtolnay/thiserror) and add more context to these exceptions. And then we just encode the errors by using the `Display` trait. So that `fn encode` will be just a `format!("{self}").encode(env)`. WDYT?

PS: we may want to remove this line after the refactor: https://github.com/elixir-nx/explorer/blob/441d21909910960d54bfb91479d3774324984c65/lib/explorer/polars_backend/shared.ex#L152

**Comment by Jhonatannunessilva** [comment]
Hey, @philss thanks!! I'm going to start doing this refactoring.
